Feature/read line
BramProvoost/ft_minishell pull request #9
Opened 2023-02-08 15:47 UTC by BramProvoost

2023-02-08 16:26 UTC, Zangetsu89 requested changes
Small changes required, but all in all what you did seems very hard, so you gotta explain to me slowly. After making changes just merge to main please.

2023-02-08 16:26 UTC, Zangetsu89 commented on srcs/main.c
> +	// tokens = tokenizer("''");	// fix empty quotes
All these comments are tests right? if yes then maybe it's better to make a separate test main file and clear this up

2023-02-08 16:26 UTC, Zangetsu89 commented on srcs/main.h
> +What is the program flow for a lexer, tokenizer and parser?
All this commented out text can be moved into a readme file

2023-02-08 16:26 UTC, Zangetsu89 commented on srcs/tokenizer/token_printer.c
> +		printf("type: %s\tlen: %li\ttext: \""GREEN"%s"NC"\"\n", type_to_string(tokens->type), tokens->len, tokens->value);
We can't use printf right?

2023-02-08 16:26 UTC, Zangetsu89 commented on srcs/tokenizer/line_functions.c
> +void	next_char(t_line *line)
What's the reason this is in a function instead of just ++ whenever is used?

2023-02-09 09:37 UTC, BramProvoost commented on srcs/main.c
> +	// tokens = tokenizer("''");	// fix empty quotes
Yes, I wil make a separate test main for that

2023-02-09 09:38 UTC, BramProvoost commented on srcs/main.h
> +What is the program flow for a lexer, tokenizer and parser?
I agree

2023-02-09 09:39 UTC, BramProvoost commented on srcs/tokenizer/token_printer.c
> +		printf("type: %s\tlen: %li\ttext: \""GREEN"%s"NC"\"\n", type_to_string(tokens->type), tokens->len, tokens->value);
That is true, this function is temporary for visualizing the tokens

2023-02-09 09:43 UTC, BramProvoost commented on srcs/tokenizer/line_functions.c
> +void	next_char(t_line *line)
I was thinking for readability

2023-02-09 10:12 UTC, Zangetsu89 approved these changes

2023-02-09 10:12 UTC, merged